const canvas=document.getElementById('orb'),ctx=canvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=reduced,w=0,h=0,angle=.4,last=0,mx=0,my=0,tx=0,ty=0;
const button=document.getElementById('motion');function buttonState(){button.textContent=paused?'Resume motion':'Pause motion';button.setAttribute('aria-pressed',String(paused))}buttonState();button.addEventListener('click',()=>{paused=!paused;buttonState()});
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(canvas);
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();tx=(e.clientX-r.left)/w-.5;ty=(e.clientY-r.top)/h-.5});canvas.addEventListener('pointerleave',()=>{tx=0;ty=0});
function point(u,v){const r=1.48+.55*Math.cos(v);let x=r*Math.cos(u),y=r*Math.sin(u),z=.55*Math.sin(v);const a=angle+mx*.7,b=.85+my*.65;let xx=x*Math.cos(a)-y*Math.sin(a),yy=x*Math.sin(a)+y*Math.cos(a);let y2=yy*Math.cos(b)-z*Math.sin(b),z2=yy*Math.sin(b)+z*Math.cos(b);const s=Math.min(w,h)*.195,depth=5.5/(5.5-z2);return{x:w*.5+xx*s*depth,y:h*.47+y2*s*depth,z:z2}}
function frame(t){requestAnimationFrame(frame);if(!w||document.hidden)return;const dt=Math.min((t-last)/1000,.05);last=t;if(!paused){angle+=dt*.15;mx+=(tx-mx)*.05;my+=(ty-my)*.05}ctx.clearRect(0,0,w,h);const surfaces=[],n=64,m=22;for(let i=0;i<n;i++)for(let j=0;j<m;j++){const u=i/n*Math.PI*2,v=j/m*Math.PI*2;const p=[point(u,v),point(u+2*Math.PI/n,v),point(u+2*Math.PI/n,v+2*Math.PI/m),point(u,v+2*Math.PI/m)];surfaces.push({p,z:p.reduce((a,b)=>a+b.z,0)/4,j,i})}surfaces.sort((a,b)=>a.z-b.z);for(const f of surfaces){const shade=Math.max(0,Math.min(1,(f.z+2)/4));const highlight=Math.pow(Math.max(0,Math.cos(f.j/m*2*Math.PI+.8)),8);ctx.beginPath();f.p.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=`rgb(${Math.round(31+shade*85+highlight*65)},${Math.round(45+shade*119+highlight*60)},${Math.round(22+shade*33+highlight*48)})`;ctx.fill();ctx.strokeStyle=`rgba(202,247,134,${.09+shade*.21})`;ctx.lineWidth=.55;ctx.stroke()} }
requestAnimationFrame(frame);
document.getElementById('copy').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText('vijayv70007@gmail.com');status.textContent='Email copied to clipboard.'}catch{status.textContent='Copy this email: vijayv70007@gmail.com'}});
document.getElementById('year').textContent=new Date().getFullYear();
if(!reduced&&matchMedia('(hover: hover)').matches)document.querySelectorAll('.skills article').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.transform=`perspective(800px) rotateX(${-(e.clientY-r.top-r.height/2)/35}deg) rotateY(${(e.clientX-r.left-r.width/2)/35}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
