// Three.js is loaded from jsDelivr so the GitHub Pages copy stays lightweight.
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/+esm';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const panel=$('#panel'),content=$('#panel-content'),help=$('#help-panel');let lastFocus=null;
const sections={
about:`<p class="panel-kicker">01 / THE OBSERVATORY</p><h2 id="panel-title">Curiosity is<br>my starting point.</h2><p>I’m <strong>Vijay Verma</strong>, an Information Technology graduate exploring how software can solve everyday problems.</p><p>I’m seeking an entry-level software or web development role where I can contribute, learn, and grow with a collaborative team.</p><div class="panel-stat"><div><strong>7.9<small> / 10</small></strong><small>B.TECH CGPA</small></div><div><strong>2025</strong><small>GRADUATING CLASS</small></div></div><div class="detail-row"><span>2021 — 2025</span><h3>B.Tech, Information Technology</h3><p>Chandigarh Engineering College, Landran<br>Mohali, Punjab</p></div><div class="detail-row"><span>2019 / 2017</span><h3>B.L.C. P.SR. School, Kunihar</h3><p>Class XII: 76.8% · Class X: 86.28%</p></div><a class="text-link" href="Vijay-Verma-Resume.pdf" download>Download my resume</a>`,
work:`<p class="panel-kicker">02 / THE ECO LAB</p><h2 id="panel-title">Small idea.<br>Meaningful impact.</h2><div class="pills"><span>Smart India Hackathon</span><span>September 2023</span></div><h3>E-Waste Collection Web Platform</h3><p>A proposed platform connecting people with on-demand e-waste collection operators, presented at the national-level Smart India Hackathon.</p><div class="detail-row"><span>MY ROLE</span><h3>Problem Research & Team Coordination</h3><ul><li>Researched the health and environmental hazards of improper e-waste disposal.</li><li>Assembled and coordinated the hackathon team.</li><li>Created and delivered the presentation to the judging panel.</li><li>Represented my college at the national-level round.</li></ul></div><p>This was a proposed platform and hackathon presentation. My contribution focused on research, coordination, and communication.</p>`,
skills:`<p class="panel-kicker">03 / THE WORKSHOP</p><h2 id="panel-title">A toolkit.<br>Always growing.</h2><h3>Programming</h3><div class="pills"><span>Python</span><span>Java</span><span>Object-Oriented Programming</span></div><h3>Web fundamentals</h3><div class="pills"><span>HTML</span><span>CSS</span><span>JavaScript</span></div><h3>Tools & concepts</h3><div class="pills"><span>VS Code</span><span>Git & GitHub · Basic</span><span>DSA · Basics</span></div><div class="detail-row"><span>HANDS-ON TRAINING</span><h3>Think Next Technology</h3><p>Web Development / Programming<br>Mohali · Remote</p><p>Structured training in programming fundamentals, independent problem solving, and hands-on project assignments while managing multiple modules and deadlines.</p></div><h3>How I work</h3><div class="pills"><span>Adaptability</span><span>Communication</span><span>Team coordination</span></div>`,
contact:`<p class="panel-kicker">04 / THE SIGNAL STATION</p><h2 id="panel-title">Good things start<br>with a hello.</h2><p>Have an opportunity, a project, or a question? I’d love to hear from you.</p><a class="primary" href="mailto:vijayv70007@gmail.com">Send an email <span>✦</span></a><a class="text-link" href="mailto:vijayv70007@gmail.com">vijayv70007@gmail.com</a><div class="contact-links"><a href="https://www.linkedin.com/in/vijay-verma2828" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="tel:+917876628354">Call me</a><button id="copy-email">Copy email</button></div><p id="copy-status" role="status"></p><div class="detail-row"><span>OPEN TO OPPORTUNITIES</span><p>Entry-level Software Development<br>Web Development</p></div><a class="text-link" href="Vijay-Verma-Resume.pdf" download>Download resume</a>`};
let focusScene=()=>{},resetScene=()=>{},setNight=()=>{},setPaused=()=>{};
function openSection(id){if(!sections[id])return;lastFocus=document.activeElement;content.innerHTML=sections[id];if(!panel.open)panel.showModal();focusScene(id);const copy=$('#copy-email');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText('vijayv70007@gmail.com');$('#copy-status').textContent='Email copied to clipboard.'}catch{$('#copy-status').textContent='Copy this address: vijayv70007@gmail.com'}}}
function closePanel(){panel.close();focusScene(null);lastFocus?.focus()}
$('#close').onclick=closePanel;panel.addEventListener('cancel',()=>focusScene(null));panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePanel()}});
$$('[data-section]').forEach(b=>b.onclick=()=>openSection(b.dataset.section));$('#help').onclick=()=>help.showModal();$('#close-help').onclick=()=>help.close();
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
let exploring=false;function explore(){if(exploring)return;exploring=true;document.body.classList.add('exploring');setTimeout(()=>window.dispatchEvent(new Event('resize')),650);toast(matchMedia('(pointer:coarse)').matches?'Use the arrow controls, or tap a station.':'WASD to drive · Drag to orbit · Tap a station to discover')}
$('#explore').onclick=explore;$('#reset').onclick=()=>{resetScene();toast('Back at the starting point.')};let night=false;$('#day').onclick=()=>{night=!night;document.body.classList.toggle('night',night);$('#day').textContent=night?'☀':'☾';$('#day').setAttribute('aria-label',night?'Switch to day':'Switch to night');$('#day').title=night?'Switch to day':'Switch to night';setNight(night)};
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;function pauseLabel(){$('#pause').textContent=paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Resume ambient animation':'Pause ambient animation');$('#pause').setAttribute('aria-pressed',String(paused));$('#pause').title=paused?'Resume ambient animation':'Pause ambient animation'}pauseLabel();$('#pause').onclick=()=>{paused=!paused;pauseLabel();setPaused(paused)};
const keys=new Set();addEventListener('keydown',e=>{if(panel.open||help.open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key)){if(document.activeElement?.tagName==='BUTTON'&&e.key.startsWith('Arrow'))return;e.preventDefault();keys.add(e.key.toLowerCase());explore()}if(e.key.toLowerCase()==='r')resetScene()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());
$$('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key.toLowerCase());explore()});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key.toLowerCase()))});
try{initWorld()}catch(err){console.error(err);$('#loading').innerHTML='<p>The 3D world isn’t available on this device.</p><a class="primary" href="resume.html">Read my portfolio</a>';$('#explore').onclick=()=>location.href='resume.html';toast('You can still explore every section using the menu.')}
function initWorld(){
const host=$('#world'),scene=new THREE.Scene();scene.background=new THREE.Color('#e9e9f3');scene.fog=new THREE.Fog('#e9e9f3',70,125);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.domElement.setAttribute('aria-label','Drive around the 3D island using W A S D or the arrow keys');host.appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-25,25,20,-20,.1,180);let zoom=1,theta=.65,phi=.78;const look=new THREE.Vector3(0,0,0),targetLook=new THREE.Vector3(0,0,0);let selected=null;
const hemi=new THREE.HemisphereLight(0xffffff,0x566b80,2.7);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff2dc,4.2);sun.position.set(-18,32,17);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:1,far:90});sun.shadow.normalBias=.035;sun.shadow.bias=-.0001;scene.add(sun);const rim=new THREE.DirectionalLight(0xab9fff,1.7);rim.position.set(16,10,-16);scene.add(rim);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.05,...extra});const m={grass:mat('#c2d6b0'),edge:mat('#dddfca'),rock:mat('#767f7e'),rock2:mat('#606776'),road:mat('#6d7784'),line:mat('#ccd0c0'),white:mat('#f3eee4'),purple:mat('#a38aca'),dark:mat('#3a4154'),mint:mat('#9fc7a3'),wood:mat('#c2a18b'),glass:mat('#788aaa',{metalness:.5,roughness:.18}),black:mat('#252d3b'),pink:mat('#de9cba'),orange:mat('#e8ab74'),screen:mat('#292f46',{emissive:'#405980',emissiveIntensity:.5}),lamp:mat('#fff6b3',{emissive:'#ffd98c',emissiveIntensity:.6}),leaf:mat('#8da89d'),leaf2:mat('#acbdd1'),water:mat('#91bfd0',{metalness:.3,roughness:.25})};
function mesh(geo,material,parent=scene,x=0,y=0,z=0){const o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
const box=(w,h,d,material,p=scene,x=0,y=0,z=0)=>mesh(new THREE.BoxGeometry(w,h,d),material,p,x,y,z);
const cyl=(rt,rb,h,material,p=scene,x=0,y=0,z=0,n=16)=>mesh(new THREE.CylinderGeometry(rt,rb,h,n),material,p,x,y,z);
const sphere=(r,material,p=scene,x=0,y=0,z=0)=>mesh(new THREE.SphereGeometry(r,16,10),material,p,x,y,z);
function group(x=0,y=0,z=0){const g=new THREE.Group();g.position.set(x,y,z);scene.add(g);return g}
function roundedShape(w,d,r){const s=new THREE.Shape(),x=-w/2,y=-d/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+d-r);s.quadraticCurveTo(x+w,y+d,x+w-r,y+d);s.lineTo(x+r,y+d);s.quadraticCurveTo(x,y+d,x,y+d-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function slab(w,d,depth,y,material,round=2,parent=scene){const o=mesh(new THREE.ExtrudeGeometry(roundedShape(w,d,round),{depth,bevelEnabled:false,curveSegments:6}),material,parent);o.rotation.x=-Math.PI/2;o.position.y=y;return o}
slab(31,24,1.2,-1.3,m.edge,3);slab(30.6,23.6,.15,-.1,m.grass,3);
const core=cyl(15.4,6,6,m.rock,scene,0,-4.2,0,7);core.scale.z=.77;core.rotation.y=.1;const under=cyl(9,1,4,m.rock2,scene,1,-8,0,6);under.scale.z=.7;
// Faceted rock shelves beneath the floating landscape.
for(let i=0;i<17;i++){const a=i/17*Math.PI*2,r=12.7;const o=mesh(new THREE.IcosahedronGeometry(1.2+(i%3)*.45,0),i%2?m.rock:m.rock2,scene,Math.cos(a)*r,-2.4-(i%3)*.5,Math.sin(a)*9.1);o.scale.y=1.8;o.rotation.set(i*.7,i*.5,0)}
const shadow=mesh(new THREE.PlaneGeometry(65,65),new THREE.ShadowMaterial({opacity:.08}),scene,0,-11,0);shadow.rotation.x=-Math.PI/2;shadow.castShadow=false;
// A connected road system through the four discovery stations.
box(26,.07,1.8,m.road,scene,0,.05,0);box(1.8,.07,19,m.road,scene,0,.06,0);for(const z of [-9,9])box(25,.07,1.6,m.road,scene,0,.05,z);for(const x of [-12,12])box(1.6,.07,18,m.road,scene,x,.05,0);
for(let i=-11;i<=11;i+=2){box(.75,.02,.06,m.line,scene,i,.1,0);box(.75,.02,.06,m.line,scene,i,.1,-9);box(.75,.02,.06,m.line,scene,i,.1,9)}for(let i=-8;i<=8;i+=2){box(.06,.02,.7,m.line,scene,0,.11,i)}
for(const z of [-1.35,1.35])for(let i=-2;i<=2;i++)box(.15,.03,.52,m.white,scene,i*.3,.11,z);
const stations=[{id:'about',name:'About me',x:-7,z:-4.7,y:5.6},{id:'work',name:'The project',x:7,z:-4.7,y:4},{id:'skills',name:'My toolkit',x:-7,z:4.7,y:4.3},{id:'contact',name:'Say hello',x:7,z:4.7,y:5.7}];const clickables=[],colliders=[],floaters=[],rotors=[];
function stationPad(s){const g=group(s.x,0,s.z);g.userData.section=s.id;clickables.push(g);colliders.push({x:s.x,z:s.z,r:2.65});const pad=cyl(3.15,3.35,.24,m.white,g,0,.16,0,48);const ring=mesh(new THREE.TorusGeometry(3.15,.045,6,64),m.purple,g,0,.31,0);ring.rotation.x=Math.PI/2;const label=document.createElement('button');label.className='station-label';label.innerHTML=`<span>${stations.indexOf(s)+1}</span>${s.name}`;label.onclick=()=>openSection(s.id);$('#labels').appendChild(label);s.label=label;s.g=g;return g}
function textTexture(text,color='#333544',background=null,w=768,h=192){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(background){ctx.fillStyle=background;ctx.fillRect(0,0,w,h)}ctx.fillStyle=color;ctx.font='bold 100px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h/2,w-35);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture}
function sign(text,w,h,parent,x,y,z,bg='#ecebdd',color='#434255'){return mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:textTexture(text,color,bg),side:THREE.DoubleSide}),parent,x,y,z)}
// Observatory: a glass dome, telescope, and a small celestial mobile.
{const g=stationPad(stations[0]);cyl(1.8,1.9,1.8,m.white,g,0,1.1,0,32);cyl(1.95,1.95,.15,m.purple,g,0,2.02,0,32);const dome=mesh(new THREE.SphereGeometry(1.8,24,12,0,Math.PI*2,0,Math.PI/2),m.glass,g,0,2.06,0);for(let a=0;a<Math.PI*2;a+=Math.PI/3){const arc=mesh(new THREE.TorusGeometry(1.82,.035,5,32,Math.PI),m.white,g,0,2.05,0);arc.rotation.y=a;arc.rotation.z=0}box(.85,1.35,.15,m.dark,g,0,.99,1.8);box(.6,.1,.7,m.white,g,0,.36,2);for(let i=0;i<3;i++)box(1.2-i*.12,.12,.35,m.white,g,0,.13+i*.1,2.5-i*.28);const telescope=group();scene.remove(telescope);g.add(telescope);telescope.position.set(.3,2.9,0);telescope.rotation.z=-.55;const scope=cyl(.24,.3,2,m.white,telescope,0,.4,0);cyl(.31,.31,.15,m.purple,telescope,0,1.4,0);cyl(.22,.22,.04,m.dark,telescope,0,1.49,0);const orbit=mesh(new THREE.TorusGeometry(.75,.035,6,32),m.orange,g,-2.1,3.6,-1.2);orbit.rotation.x=.7;floaters.push({obj:orbit,y:3.6});sphere(.2,m.orange,g,-2.1,3.6,-1.2);sign('CURIOSITY',2,.44,g,0,1.4,1.89)}
// Eco lab: solar panels, collection bins, living roof, and a wind turbine.
{const g=stationPad(stations[1]);box(3.5,1.65,2.5,m.white,g,0,1.1,0);box(3.85,.22,2.85,m.mint,g,0,2.04,0);box(1.3,1.05,.08,m.glass,g,-.65,1.1,1.28);box(.75,1.45,.1,m.purple,g,.88,1.01,1.28);sign('ECO LAB',2.2,.4,g,-.3,1.8,1.34);const solar=box(2.4,.08,1.7,m.dark,g,-.3,2.45,-.1);solar.rotation.x=.28;for(let i=0;i<4;i++){const strip=box(.025,.015,1.63,m.leaf2,solar,-.9+i*.6,.051,0)}for(let j=0;j<3;j++)box(2.35,.015,.025,m.leaf2,solar,0,.051,-.6+j*.6);for(let i=0;i<3;i++){box(.48,.62,.5,[m.mint,m.purple,m.orange][i],g,-1+i*.62,.6,1.93);box(.54,.1,.56,m.dark,g,-1+i*.62,.96,1.93)}const wind=new THREE.Group();wind.position.set(2.2,0,-1.3);g.add(wind);cyl(.06,.13,3.8,m.white,wind,0,1.9,0);const rotor=new THREE.Group();rotor.position.set(0,3.7,.12);wind.add(rotor);sphere(.17,m.purple,rotor);for(let i=0;i<3;i++){const arm=new THREE.Group();arm.rotation.z=i*Math.PI*2/3;rotor.add(arm);const blade=box(.14,1.3,.08,m.white,arm,0,.65,0);blade.rotation.z=-.12}rotors.push(rotor)}
// Workshop: an oversized terminal with a running code display.
{const g=stationPad(stations[2]);box(3.9,.25,2.4,m.wood,g,0,1.2,0);for(const x of [-1.55,1.55])for(const z of [-.8,.8])box(.17,1.05,.17,m.dark,g,x,.65,z);box(.3,.75,.22,m.dark,g,0,1.7,-.3);box(3.15,1.95,.25,m.purple,g,0,2.65,-.3);box(2.88,1.66,.04,m.screen,g,0,2.67,-.15);sign('> hello, world_',2.5,.33,g,0,3.12,-.12,'#292f46','#b7e7a3');for(let i=0;i<5;i++)box(1.2+(i%3)*.35,.06,.02,i%2?m.mint:m.pink,g,-.25+(i%2)*.15,2.76-i*.19,-.112);const kb=box(1.8,.07,.62,m.white,g,-.1,1.38,.62);for(let i=0;i<9;i++)for(let j=0;j<3;j++)box(.12,.025,.1,m.purple,g,-.85+i*.19,1.43,.42+j*.16);cyl(.2,.16,.45,m.orange,g,1.35,1.57,.45);const handle=mesh(new THREE.TorusGeometry(.13,.035,5,12),m.orange,g,1.56,1.58,.45);handle.rotation.y=Math.PI/2;box(.7,.1,.8,m.pink,g,-1.4,1.39,-.25);box(.72,.1,.8,m.mint,g,-1.4,1.49,-.3);sign('BUILD / LEARN',2.5,.35,g,0,.75,1.28)}
// Signal station: a slowly rotating satellite dish and postbox.
{const g=stationPad(stations[3]);cyl(1.15,1.45,.6,m.purple,g,0,.6,0,12);cyl(.15,.36,2.5,m.white,g,0,2,0);const dish=new THREE.Group();dish.position.set(0,3.3,0);g.add(dish);dish.rotation.x=-.45;const bowl=mesh(new THREE.SphereGeometry(1.45,24,12,0,Math.PI*2,Math.PI*.58,Math.PI*.42),m.white,dish);bowl.rotation.x=Math.PI;const inner=mesh(new THREE.SphereGeometry(1.4,24,12,0,Math.PI*2,0,Math.PI*.42),new THREE.MeshStandardMaterial({color:'#bcb0d7',side:THREE.DoubleSide,roughness:.55}),dish);inner.rotation.x=Math.PI;const ring=mesh(new THREE.TorusGeometry(1.4,.06,6,48),m.purple,dish,0,-.35,0);ring.rotation.x=Math.PI/2;cyl(.04,.04,1.3,m.dark,dish,0,-.6,0);sphere(.18,m.orange,dish,0,-1.3,0);dish.rotation.z=.35;floaters.push({obj:dish,y:3.3,dish:true});box(.8,.9,.65,m.pink,g,1.9,.92,1.15);box(.86,.12,.73,m.purple,g,1.9,1.4,1.15);box(.51,.08,.02,m.dark,g,1.9,1.17,1.485);sign('HELLO',1.7,.4,g,0,.65,1.4);const wave=mesh(new THREE.TorusGeometry(.5,.025,5,32,Math.PI*1.4),m.purple,g,-1.5,4.7,0);wave.rotation.z=-.6;floaters.push({obj:wave,y:4.7})}
function tree(x,z,size=1,variant=0){const g=group(x,0,z);cyl(.08,.14,1.2*size,m.wood,g,0,.6*size,0,6);if(variant){for(let i=0;i<3;i++)cyl((.7-i*.15)*size,0,1.1*size,m.leaf,g,0,(1.4+i*.5)*size,0,6).rotation.z=Math.PI}else{const leaf=mesh(new THREE.IcosahedronGeometry(.88*size,0),variant===2?m.leaf2:m.mint,g,0,1.55*size,0);leaf.scale.y=1.35;leaf.rotation.y=x}colliders.push({x,z,r:.45})}
[[-13,-6,1],[-12,-10,1.4],[-9,-10.5,.9],[-4,-10.1,1.2],[3,-10.3,1], [10,-10.5,.9],[13,-7,1.3],[13.5,3,1.1],[12,10.5,.8],[3,10.5,.8],[-3,10.5,1.2],[-10,10.6,1],[-13,6,1.1],[-13.7,-2,.8]].forEach(([x,z,s],i)=>tree(x,z,s,i%3));
// Quiet garden details make the world feel lived in.
for(const [x,z] of [[-3,-5],[3,5],[-10,2],[10,-2]]){const g=group(x,0,z);box(1.4,.15,.45,m.wood,g,0,.5,0);box(1.4,.4,.12,m.wood,g,0,.85,-.2);for(const a of [-.5,.5])box(.1,.5,.38,m.dark,g,a,.25,0)}
const pond=cyl(1.7,1.7,.06,m.water,scene,4,.07,3,32);pond.scale.z=.6;for(let i=0;i<8;i++){const a=i*Math.PI/4;const r=mesh(new THREE.IcosahedronGeometry(.27,0),m.white,scene,4+Math.cos(a)*1.8,.16,3+Math.sin(a)*1.1);r.scale.y=.55}
for(let i=0;i<32;i++){const x=Math.sin(i*17.3)*13,z=Math.cos(i*31.7)*10;if(Math.abs(x)<2||Math.abs(z)<1.8||stations.some(s=>Math.hypot(x-s.x,z-s.z)<3.6))continue;const o=mesh(new THREE.IcosahedronGeometry(.14,0),i%2?m.pink:m.orange,scene,x,.2,z);o.scale.y=.8}
// Street lights with emissive lamps for the night scene.
const lamps=[];for(const [x,z]of[[-1.4,-7],[1.4,7],[-10,1.4],[10,-1.4]]){cyl(.055,.085,2,m.dark,scene,x,1,z);sphere(.2,m.lamp,scene,x,2.05,z);const l=new THREE.PointLight(0xffdc96,0,5,2);l.position.set(x,2.2,z);scene.add(l);lamps.push(l)}
// Welcome sign at the back of the island.
const welcome=group(-.5,0,-10.25);for(const x of [-2.5,2.5])box(.1,1.8,.15,m.wood,welcome,x,.9,0);box(6.5,1.65,.2,m.white,welcome,0,2,0);sign('VIJAY VERMA',6,1.1,welcome,0,2.1,.11);sign('DEVELOPER • EXPLORER',5.2,.35,welcome,0,1.5,.12);
// A fully modeled rover with steerable front wheels, headlamps, and suspension motion.
const rover=group(0,0,6.6);let heading=Math.PI,speed=0;const body=new THREE.Group();rover.add(body);box(1.02,.35,1.6,m.purple,body,0,.48,0);box(.95,.18,1.65,m.white,body,0,.7,0);box(.8,.52,.84,m.purple,body,0,1,-.08);box(.68,.36,.02,m.glass,body,0,1.03,.35);box(.68,.34,.02,m.glass,body,0,1.03,-.51);box(.025,.33,.65,m.glass,body,.414,1.03,-.07);box(.025,.33,.65,m.glass,body,-.414,1.03,-.07);box(.94,.11,.99,m.white,body,0,1.31,-.08);box(1.08,.12,.16,m.dark,body,0,.45,.87);box(1.08,.12,.16,m.dark,body,0,.45,-.87);for(const x of [-.33,.33])box(.2,.12,.06,m.lamp,body,x,.7,.85);box(.42,.18,.38,m.mint,body,0,1.45,-.1);cyl(.025,.025,.6,m.dark,body,.3,1.61,-.35);sphere(.05,m.orange,body,.3,1.94,-.35);const wheels=[];for(const x of [-.6,.6])for(const z of [-.54,.54]){const axle=new THREE.Group();axle.position.set(x,.36,z);rover.add(axle);const wheel=cyl(.3,.3,.22,m.black,axle,0,0,0,16);wheel.rotation.z=Math.PI/2;const hub=cyl(.15,.15,.23,m.white,axle,0,0,0,12);hub.rotation.z=Math.PI/2;wheels.push({axle,wheel,hub,front:z>0})}
const headlights=[];for(const x of [-.33,.33]){const l=new THREE.PointLight(0xe5eaff,0,4,2);l.position.set(x,.7,1);rover.add(l);headlights.push(l)}
// Airborne clouds and a tiny looping satellite keep the island gently animated.
const clouds=[];for(const [x,y,z,s]of[[-19,7,-9,1.4],[15,9,-14,1.1],[17,1,8,.7],[-16,-2,11,.8]]){const g=group(x,y,z);for(let i=0;i<4;i++){const puff=sphere((.7+i%2*.35)*s,m.white,g,(i-1.5)*.8*s,Math.sin(i)*.2,0);puff.castShadow=false}clouds.push({g,x})}
const balloon=group(12,8,-8);sphere(.75,m.pink,balloon,0,1,0).scale.y=1.15;cyl(.3,.22,.4,m.wood,balloon,0,-.45,0,8);for(const x of [-.23,.23])cyl(.012,.012,.8,m.wood,balloon,x,0,0,4);floaters.push({obj:balloon,y:8});
let desiredNight=false;setNight=on=>{desiredNight=on;scene.background.set(on?'#242639':'#e9e9f3');scene.fog.color.copy(scene.background);hemi.intensity=on?.6:2.7;sun.intensity=on?.45:4.2;sun.color.set(on?'#9eaaff':'#fff2dc');rim.intensity=on?2:1.7;m.lamp.emissiveIntensity=on?3:.6;m.screen.emissiveIntensity=on?1.8:.5;lamps.forEach(l=>l.intensity=on?5:0);headlights.forEach(l=>l.intensity=on?3:0);renderer.toneMappingExposure=on?1.05:1.15};
function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height);const a=r.width/r.height;const size=a<.9?23:a<1.4?20:18;camera.left=-size*a;camera.right=size*a;camera.top=size;camera.bottom=-size;camera.zoom=zoom;camera.updateProjectionMatrix()}
addEventListener('resize',resize);new ResizeObserver(resize).observe(host);resize();
focusScene=id=>{selected=id;keys.clear();speed=0;if(id){const s=stations.find(s=>s.id===id);targetLook.set(s.x*.22,0,s.z*.22)}else targetLook.set(0,0,0)};
resetScene=()=>{rover.position.set(0,0,6.6);speed=0;heading=Math.PI;theta=.65;phi=.78;zoom=1;targetLook.set(0,0,0);keys.clear();resize()};
let nearby=null;$('#interact').onclick=()=>{if(nearby)openSection(nearby.id)};addEventListener('keydown',e=>{if(e.key==='Enter'&&nearby&&!panel.open&&!help.open&&document.activeElement===document.body)openSection(nearby.id)});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let dragging=false,dragMoved=0,previous={x:0,y:0};const pointers=new Map();let pinchDist=0;
const el=renderer.domElement;el.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});el.setPointerCapture(e.pointerId);dragging=true;dragMoved=0;previous={x:e.clientX,y:e.clientY};if(pointers.size===2){const p=[...pointers.values()];pinchDist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});
el.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(pinchDist)zoom=THREE.MathUtils.clamp(zoom*d/pinchDist,.7,1.8);pinchDist=d;dragMoved+=10;resize();return}if(dragging){const dx=e.clientX-previous.x,dy=e.clientY-previous.y;dragMoved+=Math.abs(dx)+Math.abs(dy);theta-=dx*.005;phi=THREE.MathUtils.clamp(phi+dy*.003,.3,1.25);previous={x:e.clientX,y:e.clientY}}});
el.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(dragMoved<6){const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(clickables,true);if(hits.length){let o=hits[0].object;while(o&&!o.userData.section)o=o.parent;if(o)openSection(o.userData.section)}}dragging=false;pinchDist=0});el.addEventListener('pointercancel',()=>{dragging=false;pointers.clear()});el.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom-e.deltaY*.001,.7,1.8);resize()},{passive:false});
// Deterministic kinematic movement, terrain limits, and building collision response.
function drive(dt,t){if(panel.open||help.open)return;const forward=keys.has('w')||keys.has('arrowup'),back=keys.has('s')||keys.has('arrowdown'),left=keys.has('a')||keys.has('arrowleft'),right=keys.has('d')||keys.has('arrowright');const acceleration=(forward?1:0)-(back?1:0);speed+=acceleration*7*dt;speed*=Math.exp(-(acceleration?1.1:4)*dt);speed=THREE.MathUtils.clamp(speed,-3.5,5);const steer=(left?1:0)-(right?1:0);if(Math.abs(speed)>.04)heading+=steer*dt*1.9*Math.sign(speed);const nx=rover.position.x+Math.sin(heading)*speed*dt,nz=rover.position.z+Math.cos(heading)*speed*dt;const blocked=Math.abs(nx)>14||Math.abs(nz)>10.3||colliders.some(c=>Math.hypot(nx-c.x,nz-c.z)<c.r+.48);if(!blocked){rover.position.x=nx;rover.position.z=nz}else speed*=-.3;rover.rotation.y=heading;body.rotation.z=-steer*speed*.012;body.position.y=Math.abs(speed)>.1?Math.sin(t*14)*.013:0;for(const w of wheels){w.axle.rotation.y=w.front?steer*.3:0;w.wheel.rotation.x+=speed*dt*3.3;w.hub.rotation.x+=speed*dt*3.3}
nearby=stations.reduce((best,s)=>{const d=Math.hypot(s.x-rover.position.x,s.z-rover.position.z);return d<5&&(!best||d<Math.hypot(best.x-rover.position.x,best.z-rover.position.z))?s:best},null);$('#nearby').hidden=!nearby;if(nearby)$('#nearby-name').textContent=nearby.name}
let time=0,last=performance.now();const v=new THREE.Vector3();let frameId=0;
function tick(now){frameId=requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;if(!paused)time+=dt;drive(dt,time);if(!paused){rotors.forEach(r=>r.rotation.z-=dt*.8);floaters.forEach((f,i)=>{f.obj.position.y=f.y+Math.sin(time*.9+i)*.15;if(f.dish)f.obj.rotation.y=Math.sin(time*.2)*.22});clouds.forEach((c,i)=>c.g.position.x=c.x+Math.sin(time*.13+i)*.8)}look.lerp(targetLook,1-Math.exp(-dt*3));const radius=48;camera.position.set(look.x+Math.sin(theta)*Math.cos(phi)*radius,look.y+Math.sin(phi)*radius,look.z+Math.cos(theta)*Math.cos(phi)*radius);camera.lookAt(look);camera.updateMatrixWorld();renderer.render(scene,camera);const rect=el.getBoundingClientRect();for(const s of stations){v.set(s.x,s.y,s.z).project(camera);const x=rect.left+(v.x*.5+.5)*rect.width,y=rect.top+(-v.y*.5+.5)*rect.height;s.label.style.left=x+'px';s.label.style.top=y+'px';s.label.style.opacity=panel.open?'0':'1';s.label.style.pointerEvents=panel.open?'none':'auto';s.label.style.visibility=x<20||x>innerWidth-20||y<80||y>innerHeight-95?'hidden':'visible'}}
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frameId);toast('The 3D view paused. Use the menu to read the portfolio.')});$('#loading').remove();tick(performance.now());
}
